import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";

import styles from "../styles/Home.module.scss";
import Link from "next/link";
import Slider from "../components/Slider";
import Advantages from "../components/Advantages";
import AccordionMy from "../components/Accordion";
import Form from "../components/FormPages";
import PhotosSwiper from "../components/PhotosSwiper";

export default function Home() {
  const [selectedLink, setSelectedLink] = useState("program");

  const handleLinkClick = (link) => {
    setSelectedLink(link);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>GastroChef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Slider />
        <Advantages />
        <PhotosSwiper />
        <div className="form__flex"x>
        <Form />
        <AccordionMy />
        </div>
        
      </div>
      <footer className={styles.footer}></footer>
    </div>
  );
}
