import Head from "next/head";
import React, { useEffect, useState } from "react";
import Image from "next/image";
import 'swiper/swiper-bundle.min.css';
import queries, { getServerAuthQuery, postQuery } from '../data/queries';
import styles from "../styles/Home.module.scss";
import Link from "next/link";
import Slider from "../components/Slider";
import Advantages from "../components/Advantages";
import AccordionMy from "../components/Accordion";
import Form from "../components/FormPages";
import PhotosSwiper from "../components/PhotosSwiper";
import Program from "../components/Program/Program";
import ProgramSlider from "../components/Program/ProgramSlider";
import authRequire from "../data/auth.require";
import tokens from '../data/tokens';

export default function Home({accordion, programs, user, photos}) {
  const [selectedLink, setSelectedLink] = useState("program");

  useEffect(() => {
    if (!user?.new_tokens) return;
    tokens.setTokens(user.new_tokens);
  }, [user]);

  return (
    <div className={styles.container}>
      <Head>
        <title>GastroChef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Slider />
        <Advantages />
        <div className={styles.program__container}>
        <ProgramSlider programs={programs} />
        </div>
        <PhotosSwiper photos={photos}/>
        <div className="form__flex"x>
        <Form />
        <AccordionMy accordion={accordion}/>
        </div>
        
      </div>
      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps({ req,res }) {
  const user = await authRequire(req, res);
  const res1 = await queries.get('/faq');
  const res2 = await getServerAuthQuery(req, '/mealplan');
  const photos = await postQuery('/gallery/getall');
  return {
    props: {
      user: user || null,
      accordion: res1.data,
      programs: res2.data,
      photos: photos.data
    },
  };
}